# Generated by Django 4.0.5 on 2023-07-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.FileField(upload_to='mymedia/'),
        ),
    ]
