# Generated by Django 4.0.5 on 2023-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_students_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.FileField(upload_to='mymedia/'),
        ),
    ]
